### ISSUE TITLE
Redirect to sign in

### ISSUE THREAD

**Issue by iammenasco** [sleeveup/sleeveup-app#11]
On any page, if the user is not logged in redirect them to the sign in page

**Comment by ardeay** [comment]
I added this 
`     if ( angular.isDefined($localStorage.token) ) {
        $scope.app.user = {
          username: $localStorage.username,
          avatar:  $localStorage.avatar
        }
      } else {
        $state.go('access.signin');
      }`

in the file https://github.com/sleeveup/sleeveup-app/blob/master/src/js/main.js#L67

Need a logout to test it, it may work?

**Comment by iammenasco** [comment]
Its not working for me yet. If I load the dashboard without the token in local storage, it does not redirect me anywhere.

**Comment by ardeay** [comment]
That state.go isn't firing, but the logic is going there

**Comment by iammenasco** [comment]
@ardeay - Please verify, this should be working now.
